#!/usr/bin/env bash
# Writes android/keystore.properties with an absolute storeFile path.
# Usage:
#   ./scripts/setup-android-release-keystore.sh
#   ./scripts/setup-android-release-keystore.sh /path/to/upload-keystore.jks

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ANDROID_DIR="${ROOT}/android"
PROPS_FILE="${ANDROID_DIR}/keystore.properties"
EXAMPLE_FILE="${ROOT}/android-keystore.properties.example"
DEFAULT_KEYSTORE="${HOME}/upload-keystore.jks"
KEYSTORE_PATH="${1:-$DEFAULT_KEYSTORE}"

# Expand leading ~
if [[ "${KEYSTORE_PATH}" == ~* ]]; then
  KEYSTORE_PATH="${KEYSTORE_PATH/#\~/$HOME}"
fi

# Resolve to absolute
if [[ "${KEYSTORE_PATH}" != /* ]]; then
  KEYSTORE_PATH="$(cd "$(dirname "${KEYSTORE_PATH}")" && pwd)/$(basename "${KEYSTORE_PATH}")"
fi

if [[ ! -f "${KEYSTORE_PATH}" ]]; then
  echo "error: keystore not found at: ${KEYSTORE_PATH}" >&2
  echo "Place your Play upload keystore at ~/upload-keystore.jks (or pass a path)." >&2
  exit 1
fi

if [[ ! -d "${ANDROID_DIR}" ]]; then
  echo "error: ${ANDROID_DIR} missing. Run: npx expo prebuild --platform android --clean" >&2
  exit 1
fi

STORE_PASSWORD="${STORE_PASSWORD:-}"
KEY_ALIAS="${KEY_ALIAS:-}"
KEY_PASSWORD="${KEY_PASSWORD:-}"

if [[ -f "${PROPS_FILE}" ]]; then
  # Preserve existing secrets when re-running.
  STORE_PASSWORD="${STORE_PASSWORD:-$(sed -n 's/^storePassword=//p' "${PROPS_FILE}" | head -n1)}"
  KEY_ALIAS="${KEY_ALIAS:-$(sed -n 's/^keyAlias=//p' "${PROPS_FILE}" | head -n1)}"
  KEY_PASSWORD="${KEY_PASSWORD:-$(sed -n 's/^keyPassword=//p' "${PROPS_FILE}" | head -n1)}"
fi

if [[ -z "${STORE_PASSWORD}" || -z "${KEY_ALIAS}" || -z "${KEY_PASSWORD}" ]]; then
  if [[ -f "${EXAMPLE_FILE}" ]]; then
    echo "Fill passwords interactively (or export STORE_PASSWORD / KEY_ALIAS / KEY_PASSWORD)."
  fi
  if [[ -z "${STORE_PASSWORD}" ]]; then
    read -r -s -p "storePassword: " STORE_PASSWORD
    echo
  fi
  if [[ -z "${KEY_ALIAS}" ]]; then
    read -r -p "keyAlias: " KEY_ALIAS
  fi
  if [[ -z "${KEY_PASSWORD}" ]]; then
    read -r -s -p "keyPassword: " KEY_PASSWORD
    echo
  fi
fi

cat > "${PROPS_FILE}" <<EOF
# Generated by scripts/setup-android-release-keystore.sh
# storeFile is an absolute path on purpose — Gradle does not expand ~/.
storeFile=${KEYSTORE_PATH}
storePassword=${STORE_PASSWORD}
keyAlias=${KEY_ALIAS}
keyPassword=${KEY_PASSWORD}
EOF

chmod 600 "${PROPS_FILE}"
echo "Wrote ${PROPS_FILE}"
echo "storeFile=${KEYSTORE_PATH}"
